config/routes.rb
Rails.application.routes.draw do
  resources :expensives
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "expensives#index"
  resources :categories
  resources :subcategories

 # map.connect 'api/catalog/:id', :controller => 'catalog', :action => 'getSubcategories'

  namespace :api, :except => [:new, :edit, :index, :create, :update, :destroy, :show] do
    get 'catalog/getSubcategories/:id', :to => 'catalog#getSubcategories', :defaults => {:format => 'json'}

  end
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category, :class_name => "Category", :foreign_key => "category_id" #,:inverse_of => Subcategory
  #has_one Category
  #has_one :Category , :inverse_of => Subcategory
  #has_one :category, :class_name => "Category", :foreign_key => "category_id" ,:inverse_of => Subcategory
  def to_s
    self.Name
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController

  def index
    @subcategories = Subcategory.all
  end

  def show
    @subcategory = Subcategory.find(params[:id])
  end

  def new
    @subcategory = Subcategory.new()
    respond_to do |format|
      format.html { render layout: false }
      format.json { render json: @subcategory }
    end

  end

  def edit
    @subcategory = Subcategory.find(params[:id])
  end

  def update
    @subcategory = Subcategory.find(params[:id])

    if @subcategory.update_attributes(subcategory_params)
      flash[:success] = "subCategory success!"
    #  redirect_to subcategories_path(@subcategory)
    #else
    #  render 'new'
    end
    redirect_to categories_url
  end

  def create
    @subcategory = Subcategory.new(subcategory_params)
    if @subcategory.save
      flash[:success] = "subCategory success!"
    #  redirect_to (@subcategory)
    #else
    #  render 'new'
    end
    redirect_to categories_url
  end

  def destroy
    item = Subcategory.find(params[:id])

    respond_to do |format|
      if item.destroy
        msg = {status: :ok, :message => "Success!", html: "<b>Done!</b>"}
        format.json { render json: msg }
      else
        format.json { render json: item.errors, status: :unprocessable_entity }
      end

    end
  end

  private
  def subcategory_params
    #params.require(:subcategory).permit(:Name, :categories_id)

    params.require(:subcategory).permit(:Name, :category_id)

  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory, :html => {:class => "form-inline"}) do |f| %>
    <div class="form-group">
      <% if @subcategory.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

            <ul>
              <% @subcategory.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>
    <div class="field form-group">
      <%= f.text_field :Name, placeholder: "Enter a Subcategory name...", class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: "Select a Category"}, class: "form-control") %>
    </div>

    <div class="form-group text-right">
      <%= f.submit "Save", :class => "btn btn-primary" %>
    </div>

<% end %>

app/views/subcategories/create.html.erb
<h1>Subcategories#create</h1>
<p>Find me in app/views/subcategories/create.html.erb</p>

app/views/subcategories/destroy.html.erb
<h1>Subcategories#destroy</h1>
<p>Find me in app/views/subcategories/destroy.html.erb</p>

app/views/subcategories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<h1>Subcategories</h1>
<%= link_to "New Subcategory", new_subcategory_path %>
<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.id %></td>
        <td><%= subcategory.Name %></td>
        <td><%= link_to "Show", subcategory_path(subcategory) %></td>
        <td><%= link_to "Edit", edit_subcategory_path(subcategory) %></td>
        <td><%= link_to "Remove", subcategory, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
  <% end %>
</table>

app/views/subcategories/new.html.erb
<h1>New SubCategory</h1>
<%= render 'form' %>
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<h1>Category</h1>
<h3><%=@subcategory.Name %></h3>
</br>
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/update.html.erb
<h1>Subcategories#update</h1>
<p>Find me in app/views/subcategories/update.html.erb</p>