config/routes.rb
Rails.application.routes.draw do
  resources :expensives
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "expensives#index"
  resources :categories
  resources :subcategories

 # map.connect 'api/catalog/:id', :controller => 'catalog', :action => 'getSubcategories'

  namespace :api, :except => [:new, :edit, :index, :create, :update, :destroy, :show] do
    get 'catalog/getSubcategories/:id', :to => 'catalog#getSubcategories', :defaults => {:format => 'json'}

  end
end

app/models/expensive.rb
class Expensive < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory

  validates :amount, :logdate, :category, :subcategory, :presence => true


  filterrific(
      default_filter_params: {sorted_by: 'logdate_desc'},
      available_filters: [
          :sorted_by,
          :search_query,
          :with_category_id
      ]
  )

  scope :search_query, lambda { |query|
# Filters students whose name or email matches the query
    return nil if query.blank?

    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)

    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conds = 1
    where("LOWER(expensives.note) LIKE ? ", terms)


  }
  scope :sorted_by, lambda { |sort_option|
    # Sorts students by sort_key

    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
=begin
      when /^created_at_/
        order("expensives.created_at #{ direction }")
=end
      when /^logdate_/
        #when /^created_at_/
        # Simple sort on the created_at column.
        # Make sure to include the table name to avoid ambiguous column names.
        # Joining on other tables is quite common in Filterrific, and almost
        # every ActiveRecord table has a 'created_at' column.
        order("expensives.logdate #{ direction }")
      when /^amount_/
        # Simple sort on the name colums
        order("expensives.amount #{ direction }")
      when /^note_/
        # Simple sort on the name colums
        order("expensives.note #{ direction }")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end

  }
  scope :with_category_id, lambda { |category_ids|
    # Filters students with any of the given category_ids
    where("expensives.category_id = ?", category_ids)

  }

  # This method provides select options for the `sorted_by` filter select input.
  # It is called in the controller as part of `initialize_filterrific`.
  def self.options_for_sorted_by
    [

        ['Note (a-z)', 'note_asc'],
        ['Log date (newest first)', 'logdate_desc'],
        ['Log date (oldest first)', 'logdate_asc'],
        ['Amount (lowest)', 'amount_asc'],
        ['Amount (higest)', 'amount_desc'],
    ]
  end

=begin
  def self.options_for_select
    order('name').map { |e| [e.name, e.id] }
  end
=end

end

app/controllers/expensives_controller.rb
class ExpensivesController < ApplicationController
  before_action :set_expensive, only: [:show, :edit, :update, :destroy]

  # GET /expensives
  # GET /expensives.json
  def index

    @filterrific = initialize_filterrific(
        Expensive,
        params[:filterrific],
        select_options: {
            sorted_by: Expensive.options_for_sorted_by,
            with_category_id: Category.options_for_select
        },
        persistence_id: 'shared_key',
        default_filter_params: {}
    ) or return
    @expensives = Expensive.filterrific_find(@filterrific).page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end

  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  # GET /expensives/1
  # GET /expensives/1.json
  def show
  end

  # GET /expensives/new...

  def new
    @expensive = Expensive.new
    respond_to do |format|
      format.html { render layout: false }
      format.json { render json: @expensive }
    end
  end

  # GET /expensives/1/edit
  def edit
  end

  # POST /expensives
  # POST /expensives.json
  def create
    @expensive = Expensive.new(expensive_params)

    if @expensive.save

      #format.html { redirect_to index, notice: 'Expense was successfully created.' }
      #format.html { render action: 'index', status: :created, location: @expensives }
      #format.json { render action: 'index', status: :created, location: @expensives }
      # added:
      #format.js { render action: 'index', status: :created, location: @expensives}
      redirect_to expensives_url
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @expensive.errors, status: :unprocessable_entity }
        format.js { render json: @expensive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expensives/1
  # PATCH/PUT /expensives/1.json
  def update

    if @expensive.update(expensive_params)
      #format.html { redirect_to @expensive, notice: 'Expensive was successfully updated.' }
      #format.json { render :show, status: :ok, location: @expensive }
      redirect_to expensives_url
    else
      respond_to do |format|
        #format.html { render :edit }
        format.json { render json: @expensive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expensives/1
  # DELETE /expensives/1.json
  def destroy
    @expensive.destroy
    respond_to do |format|
      format.html { redirect_to expensives_url, notice: 'Expensive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_expensive
    @expensive = Expensive.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def expensive_params
    params.require(:expensive).permit(:amount, :logdate, :note, :category_id, :subcategory_id)
  end

end

app/helpers/expensives_helper.rb
module ExpensivesHelper
end

app/views/expensives/_filter.html.erb
<!-- Filter -->
<div class="cd-filter">
  <%= form_for_filterrific @filterrific do |f| %>
      <%= link_to(
              'Reset filters',
              reset_filterrific_url,
              class: "js-reset-filter",
              remote: true
          ) %>
      <div class="cd-filter-block">
        <h4>Search</h4>
        <div class="cd-filter-content search-input">
          <%= f.text_field(
                  :search_query,
                  class: 'filterrific-periodically-observed form-control',
                  type: 'search',
                  placeholder: "Search in my notes..."
              ) %>
          <!-- </label>-->
        </div> <!-- cd-filter-content -->
      </div> <!-- cd-filter-block -->

      <div class="cd-filter-block hidden">
        <h4>Months</h4>

        <ul class="cd-filter-content cd-filters list">
          <li>
            <input class="filter" data-filter=".check1" type="checkbox" id="checkbox1">
            <label class="checkbox-label" for="checkbox1">January</label>
          </li>

          <li>
            <input class="filter" data-filter=".check2" type="checkbox" id="checkbox2">
            <label class="checkbox-label" for="checkbox2">February</label>
          </li>

          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">March</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">April</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">May</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">June</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">July</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">August</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">September</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">October</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">November</label>
          </li>
          <li>
            <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
            <label class="checkbox-label" for="checkbox3">December</label>
          </li>
        </ul> <!-- cd-filter-content -->
      </div> <!-- cd-filter-block -->

      <div class="cd-filter-block">
        <h4><label for="sorted_by">Sorted by</label></h4>
        <div class="cd-filter-content">
          <div class="cd-filters">
            <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], class: 'filter') %>
          </div> <!-- cd-select -->
        </div> <!-- cd-filter-content -->
      </div> <!-- cd-filter-block -->
      <div class="cd-filter-block">
        <h4><label for="with_category_id" class="control-label">Filtered by</label></h4>
        <div class="cd-filter-content">
          <div class="cd-filters">
            <%= f.select(
                    :with_category_id,
                    @filterrific.select_options[:with_category_id],
                    include_blank: 'All') %>
          </div>
        </div>
      </div>

      <div class="cd-filter-block hidden">
        <h4>Radio buttons</h4>

        <ul class="cd-filter-content cd-filters list">
          <li>
            <input class="filter" data-filter="" type="radio" name="radioButton" id="radio1" checked>
            <label class="radio-label" for="radio1">All</label>
          </li>

          <li>
            <input class="filter" data-filter=".radio2" type="radio" name="radioButton" id="radio2">
            <label class="radio-label" for="radio2">Choice 2</label>
          </li>

          <li>
            <input class="filter" data-filter=".radio3" type="radio" name="radioButton" id="radio3">
            <label class="radio-label" for="radio3">Choice 3</label>
          </li>
        </ul> <!-- cd-filter-content -->
      </div> <!-- cd-filter-block -->
      <%= render_filterrific_spinner %>
  <% end %>
  <a href="#0" class="cd-close">Close</a>
</div> <!-- cd-filter -->

<a href="#0" class="cd-filter-trigger">Filters</a>

app/views/expensives/_form.html.erb
<%= form_for @expensive, remote: true, :html => {role: :form, :class => "form-horizontal", 'data-model' => 'expensive'} do |f| %>

    <div class="form-group">
      <% if expensive.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@expensive.errors.count, "error") %> prohibited this expenses from being saved:</h2>

            <ul>
              <% @expensive.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>
    <div class="field form-group">
      <%= f.label :amount, :class => "control-label" %>
      <%= f.number_field :amount, :class => "form-control", min: 0, value: number_to_currency(f.object.amount.to_f, delimiter: '', unit: ''), step: :any %>
      <span class="help-block"></span>
    </div>

    <div class="field form-group">
      <%= f.label :logdate, :class => "control-label" %>
      <div class="calendar-pickup">
        <%= f.date_field :logdate, :class => "form-control", placeholder: "MM-dd-yyyy" %>
        <span class="help-block"></span>
      </div>
    </div>

    <div class="field form-group">
      <%= f.label :note, :class => "control-label" %>
      <%= f.text_area :note, :class => "form-control" %>
      <span class="help-block"></span>
    </div>

    <div class="field form-group">
      <%= f.label :Category, :class => "control-label" %><br/>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: "Select a Category"}, {:class => "form-control"}) %>
      <span class="help-block"></span>
    </div>

    <div class="field form-group">
      <%= f.label :Subcategory, :class => "control-label" %><br/>
      <%= f.collection_select(:subcategory_id, {}, :id, :Name, {include_blank: "Select a Subcategory"}, :class => "form-control") %>
      <span class="help-block"></span>
    </div>
    <div class="js-new-subcategory form-group">
      <%= link_to "New Subcategory", new_subcategory_path, class: "btn btn-primary" %>
    </div>
    <div class="form-group text-right">
      <%= button_tag type: 'submit', class: "btn btn-primary" do %>
          <i class="fa fa-floppy-o" aria-hidden="true"></i> Save
      <% end %>
    </div>
<% end %>

app/views/expensives/_list.erb
<div id="container-expensive">
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= filterrific_sorting_link(@filterrific, :amount) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :logdate) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :note) %></th>
      <th>Category</th>
      <th>Subcategory</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @expensives.each do |expensive| %>
        <tr>
          <td><%= number_to_currency(expensive.amount) %></td>
          <td><%= expensive.logdate.try(:strftime, '%m-%d-%Y') %></td>
          <td><%= expensive.note %></td>
          <td><%= expensive.category %></td>
          <td><%= expensive.subcategory %></td>
          <td>
            <a href="<%= expensife_path(expensive) %>" class="btn btn-info" role="button">
              <i class="fa fa-info" aria-hidden="true"></i></a>
          <td>
            <a href="<%= edit_expensife_path(expensive) %>" class="btn btn-success" role="button">
              <i class="fa fa-pencil" aria-hidden="true"></i></a>
          </td>
          <td>
            <a href="#" class="btn btn-danger js-delete-expense" role="button"
              data-message="Are you sure to delete this log: $ <%= expensive.amount %>"
              data-id="<%= expensive.id %>"><i class="fa fa-trash" aria-hidden="true"></i></a>

          </td>
        </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="4"><%= paginate @expensives, remote: true %></td>
      <td colspan="4" class="text-right"><%= page_entries_info @expensives, entry_name: 'item' %></td>
    </tr>
    </tfoot>
  </table>
</div>

app/views/expensives/edit.html.erb
<h1>Editing Expensive</h1>

<%= render 'form', expensive: @expensive %>

<%= link_to 'Show', @expensive %> |
<%= link_to 'Back', expensives_path %>

app/views/expensives/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <h1>My registered expenses</h1>
    <hr>
  </div>
</div>

<br>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <button id='btnAddNewExpensive' class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Add Expense Log
        </button>
        <button id='btnAddNewExpensive' class="btn btn-info hidden">
          <i class="fa fa-file-excel-o" aria-hidden="true"></i>
          Import from Excel
        </button>

        <%= render(
                partial: 'expensives/list',
                locals: {expensives: @expensives}
            ) %>
      </div>
    </div>
  </div>
</div>

<!-- Filter -->
<%= render 'expensives/filter' %>

app/views/expensives/index.js.erb
<%# app/views/expensives/index.js.erb %>
<% js = escape_javascript(
    render(partial: 'expensives/list', locals: { expensives: @expensives})
) %>

$("#container-expensive").html("<%= js %>");

$('#paginator').html('<%= escape_javascript(paginate(@expensives, :remote => true).to_s) %>');

app/views/expensives/new.html.erb
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <h1>New Expensive</h1>
      <%= render 'form', expensive: @expensive %>

      <%= link_to 'Back', expensives_path %>
    </div>
  </div>

app/views/expensives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @expensive.amount %>
</p>

<p>
  <strong>Logdate:</strong>
  <%= @expensive.logdate %>
</p>

<p>
  <strong>Note:</strong>
  <%= @expensive.note %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expensive.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @expensive.subcategory %>
</p>

<%= link_to 'Edit', edit_expensife_path(@expensive) %> |
<%= link_to 'Back', expensives_path %>

app/views/expensives/show.js.erb
<%# app/views/expensives/show.js.erb %>
<% js = escape_javascript(
    render(partial: 'expensives/list', locals: { expensives: @expensives})
) %>

$("#container-expensive").html("<%= js %>");

$('#paginator').html('<%= escape_javascript(paginate(@expensives, :remote => true).to_s) %>');