config/routes.rb
Rails.application.routes.draw do
  resources :expensives
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "expensives#index"
  resources :categories
  resources :subcategories

 # map.connect 'api/catalog/:id', :controller => 'catalog', :action => 'getSubcategories'

  namespace :api, :except => [:new, :edit, :index, :create, :update, :destroy, :show] do
    get 'catalog/getSubcategories/:id', :to => 'catalog#getSubcategories', :defaults => {:format => 'json'}

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My Expenses Log</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>  <a href="/"><i class="fa fa-table" aria-hidden="true"></i> Expenses loged</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-tasks" aria-hidden="true"></i> Category <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add Category", new_category_path %></li>
            <li><%= link_to "Show Categories", categories_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome BG <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>